# Generated by Django 3.1.5 on 2022-06-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20220601_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='percent',
        ),
    ]
